CREATE TABLE IF NOT EXISTS `ROLE` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `NAME` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '')
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `USERS` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `EMAIL` VARCHAR(45) NOT NULL COMMENT '',
  `NAME` VARCHAR(45) NULL COMMENT '',
  `ROLE_ID` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  INDEX `fk_USER_TO_ROLE_idx` (`ROLE_ID` ASC)  COMMENT '',
  CONSTRAINT `fk_USER_TO_ROLE`
    FOREIGN KEY (`ROLE_ID`)
    REFERENCES `ROLE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

insert into `ROLE` (`NAME`) values ('user');
insert into `ROLE` (`NAME`) values ('admin');

insert into `USERS` (`EMAIL`, `NAME`, `ROLE_ID`) VALUES ('admin@freelancing.com', 'admin', 2);
